language: node_js
node_js: 'node'
script: npm run build
before_deploy:
  - sed -i '/\*.bundle.js/d' .gitignore # removes all *.bundle.js files from gitignore
  - sed -i '/*.tests.js/d' .gitignore   # removes *.tests.js files from gitignore
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
